bat_num: 0
bool_rel_paths: true
bool_shw_notes: true
bool_summ_rows: true
bool_unused_1: false
bool_unused_2: false
bool_unused_3: false
c_date: '2025-06-01 22:11:47'
cfg_sys_id: v_chk
cfg_sys_ver: '0.7'
ctot:
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
dir_batch: G:\dev\PycharmProjects\obsidian-vault-health-check\data\batch_files\
dir_templates: E:\o2\z_meta\templates
dir_vault: E:\o2
dir_wbs: G:\dev\PycharmProjects\obsidian-vault-health-check\data\workbooks\
dirs_dot:
- .makemd
- .obsidian
- .obsidian_cfg
- .trash
- .vs
- .vscode
dirs_skip_abs_lst:
- E:\o2\z_meta
- E:\o2\z_resources
dirs_skip_rel_str: z_meta, z_resources
max_links_tags: 0
max_links_vals: 0
pn_batch: ''
pn_cfg: G:\dev\PycharmProjects\obsidian-vault-health-check\CONFIG.yaml
pn_wb_exec: C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE
pn_wbs: ''
tab_seq:
- pros
- vals
- tags
- file
- code
- xyml
- dups
- tmpl
- nest
- plug
- summ
- ar51
vault_id: ''
