bat_dir: G:\dev\PycharmProjects\obsidian-vault-health-check\data\batch_files\
bat_num: 0
bat_pname: ''
bool_rel_paths: true
bool_shw_notes: true
bool_summ_rows: true
bool_unused_1: false
bool_unused_2: false
bool_unused_3: false
c_date: '2025-06-01 11:04:19'
cfg_pname: G:\dev\PycharmProjects\obsidian-vault-health-check\CONFIG.yaml
cfg_sys_id: v_chk
cfg_sys_ver: '0.7'
ctot:
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
dirs_dot:
- .makemd
- .obsidian
- .obsidian_cfg
- .trash
- .vs
- .vscode
dirs_skip_abs_lst:
- E:\o2\z_meta
- E:\o2\z_resources
dirs_skip_rel_str: z_meta, z_resources
tab_seq:
- pros
- vals
- tags
- file
- code
- xyml
- dups
- tmpl
- nest
- plug
- summ
- ar51
tmpldir: E:\o2\z_meta\templates
vault_id: ''
vault_path: E:\o2
wb_exec_path: C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE
xls_dir: G:\dev\PycharmProjects\obsidian-vault-health-check\data\workbooks\
xls_pname: ''
