cfg:
  cfg_sys_id: v_chk
  cfg_sys_ver: 1.0.1
  c_date: '2025-05-22 19:32:02'
  vault_id: o2
  vault_path: E:\o2\
  cfg_dir: G:\dev\v_chk\data\cfgs\
  xls_dir: G:\dev\v_chk\data\xlWork\
  tmpldir: z_meta/templates/
  xl_exec_path: C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE
  tab_seq:
  - pros
  - vals
  - tags
  - file
  - code
  - xyml
  - dups
  - tmpl
  - nest
  - plug
  - summ
  - ar51
  ctot:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
